### ISSUE TITLE
报错了日志

### ISSUE THREAD

**Issue by ling-shi-cyber** [HydroGest/YesImBot#10]
AggregateError
                            at AxiosError.from (/root/.koishi/data/instances/default/node_modules/axios/dist/node/axios.cjs:841:14)
                            at RedirectableRequest.handleRequestError (/root/.koishi/data/instances/default/node_modules/axios/dist/node/axios.cjs:3106:25)
                            at RedirectableRequest.emit (node:events:518:28)
                            at eventHandlers.<computed> (/root/.koishi/data/instances/default/node_modules/follow-redirects/index.js:38:24)
                            at ClientRequest.emit (node:events:518:28)
                            at TLSSocket.socketErrorListener (node:_http_client:500:9)
                            at TLSSocket.emit (node:events:518:28)
                            at emitErrorNT (node:internal/streams/destroy:169:8)
                            at emitErrorCloseNT (node:internal/streams/destroy:128:3)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
                            at Axios.request (/root/.koishi/data/instances/default/node_modules/axios/dist/node/axios.cjs:4224:41)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async run (/root/.koishi/data/instances/default/node_modules/koishi-plugin-yesimbot/lib/index.js:198:22)
                            at async /root/.koishi/data/instances/default/node_modules/koishi-plugin-yesimbot/lib/index.js:464:22
                            at async next (/root/.koishi/data/instances/default/node_modules/@koishijs/core/lib/index.cjs:857:16)
                            at async next (/root/.koishi/data/instances/default/node_modules/@koishijs/core/lib/index.cjs:857:16)
                            at async /root/.koishi/data/instances/default/node_modules/koishi-plugin-dialogue/lib/index.js:596:12
                            at async next (/root/.koishi/data/instances/default/node_modules/@koishijs/core/lib/index.cjs:857:16)
                            at async next (/root/.koishi/data/instances/default/node_modules/@koishijs/core/lib/index.cjs:857:16)
                            at async next (/root/.koishi/data/instances/default/node_modules/@koishijs/core/lib/index.cjs:857:16)

**Comment by HydroGest** [comment]
请试试最新版本
