### ISSUE TITLE
 AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by XUANHLGG** [HydroGest/YesImBot#19]
AxiosError: Request failed with status code 404
                            at settle (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:2019:12)
                            at IncomingMessage.handleStreamEnd (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:3135:11)
                            at IncomingMessage.emit (node:events:530:35)
                            at endReadableNT (node:internal/streams/readable:1696:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
                            at Axios.request (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:4287:41)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async run (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-yesimbot\lib\index.js:113:22)
                            at async C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-yesimbot\lib\index.js:563:22
                            at async next (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async Processor._handleMessage (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:835:22)

不清楚是不是网络环境问题？API 用的是 GPT 神 GPT-4o-mini
感谢

**Comment by HydroGest** [comment]
版本是什么

**Comment by HydroGest** [comment]
给一下 API 相关配置

**Comment by XUANHLGG** [comment]
> 版本是什么

1.4.0

**Comment by XUANHLGG** [comment]
> 给一下 API 相关配置

![image](https://github.com/user-attachments/assets/7ceae5e7-12a8-403c-8652-37cc9132e17b)

**Comment by HydroGest** [comment]
试试 APIType 填 OpenAI，然后 https://api.gptgod.online

**Comment by XUANHLGG** [comment]
> 试试 APIType 填 OpenAI，然后 https://api.gptgod.online

改报403了😂

AxiosError: Request failed with status code 403
                            at settle (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:2019:12)
                            at BrotliDecompress.handleStreamEnd (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:3135:11)
                            at BrotliDecompress.emit (node:events:530:35)
                            at endReadableNT (node:internal/streams/readable:1696:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
                            at Axios.request (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:4287:41)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async run (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-yesimbot\lib\index.js:113:22)
                            at async C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-yesimbot\lib\index.js:632:22
                            at async next (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async Processor._handleMessage (C:\Users\Xuan\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:835:22)

**Comment by XUANHLGG** [comment]
> 试试 APIType 填 OpenAI，然后 https://api.gptgod.online

可以了，我将`AIModel`改成全小写`gpt-4o-mini`解决了😂
