### ISSUE TITLE
[CloudFlare API] 返回消息为空

### ISSUE THREAD

**Issue by Vincent-the-gamer** [HydroGest/YesImBot#20]
操作系统：Arch Linux

Node.js版本：v20.18.0

插件版本：1.4.0-preview  直接克隆的GitHub项目，未通过Koishi插件市场安装

使用的API： Cloudflare， 已确保BaseURL, UID, API Key无误。

模型： @cf/meta/llama-3-8b-instruct

Prompt: 自动下载的Prompt-next-short.mdt

已确保请求正确发起。

日志如下(路径已做脱敏处理)：

```
15 / 15
string
2024-10-30 10:23:13 [W] session 买不起ww
                        SyntaxError: Unexpected end of JSON input
                            at JSON.parse (<anonymous>)
                            at handleResponse (插件路径/yesimbot/src/utils/content.ts:53:28)
                            at <anonymous> (插件路径/yesimbot/src/index.ts:185:13)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async next (xxx/node_modules/.pnpm/@koishijs+core@4.18.0/node_modules/@koishijs/core/src/middleware.ts:258:16)
                            at async next (/home/xxx/Downloads/deploy-codes/xxx/node_modules/.pnpm/@koishijs+core@4.18.0/node_modules/@koishijs/core/src/middleware.ts:258:16)
                            at async next (/home/xxx/Downloads/deploy-codes/xxx/node_modules/.pnpm/@koishijs+core@4.18.0/node_modules/@koishijs/core/src/middleware.ts:258:16)
                            at async next (/home/xxx/Downloads/deploy-codes/xxx/node_modules/.pnpm/@koishijs+core@4.18.0/node_modules/@koishijs/core/src/middleware.ts:258:16)
                            at async next (/home/xxx/Downloads/deploy-codes/xxx/node_modules/.pnpm/@koishijs+core@4.18.0/node_modules/@koishijs/core/src/middleware.ts:258:16)
                            at async Processor._handleMessage (/home/xxx/Downloads/deploy-codes/xxx/node_modules/.pnpm/@koishijs+core@4.18.0/node_modules/@koishijs/core/src/middleware.ts:269:22)
```

初步定位是这里的问题：

![QQ_1730255701689](https://github.com/user-attachments/assets/17f445b7-bad2-465d-b9b7-3028d844cabb)

进一步对res进行console.log，发现回复消息为空

![QQ_1730257546303](https://github.com/user-attachments/assets/10b1a9e9-31c3-46de-88fe-80234f3d333f)

![QQ_1730258084760](https://github.com/user-attachments/assets/49f88c1e-c34d-4658-a76d-f16d92554ef8)

打印input整个对象, 返回值为：

```json
{
    result: {
         response: ''
    },
    success: true,
    errors: [],
    messages: []
}
```

**Comment by Vincent-the-gamer** [comment]
补充：GPT God没有问题，目前切换至GPT God使用

**Comment by HydroGest** [comment]
Cloudflare 提供的免费模型不够智能，已不适用当前的 Prompt 长度。你可以魔改 Prompt 但事实证明效果不是很好。
