### ISSUE TITLE
[bug] finalReplyId和groupId不一致时，报错

### ISSUE THREAD

**Issue by Touch-Night** [HydroGest/YesImBot#62]
https://github.com/HydroGest/YesImBot/blob/3625be3e5ed0c594397ce6478de663fe4a321fec/src/index.ts#L499
在finalReplyTo为"private:1762918301"，且groupId为"186782726"时报错如下：
```
RangeError: The number NaN cannot be converted to a BigInt because it is not an integer
                            at BigInt (<anonymous>)
                            at Internal.prepareArg (E:\Koishi\dev\yesimbot\node_modules\koishi-plugin-adapter-onebot\lib\index.js:142:13)
                            at _Internal.<computed> [as sendGroupMsg] (E:\Koishi\dev\yesimbot\node_modules\koishi-plugin-adapter-onebot\lib\index.js:162:52)
                            at OneBotMessageEncoder.flush (E:\Koishi\dev\yesimbot\node_modules\koishi-plugin-adapter-onebot\lib\index.js:763:354)
                            at OneBotMessageEncoder.send (E:\Koishi\dev\yesimbot\node_modules\@satorijs\core\src\message.ts:54:16)
                            at async Proxy.sendMessage (E:\Koishi\dev\yesimbot\node_modules\@satorijs\core\src\bot.ts:188:22)
                            at async <anonymous> (E:\Koishi\dev\yesimbot\external\yesimbot\src\index.ts:502:24)
                            at async next (E:\Koishi\dev\yesimbot\node_modules\@koishijs\core\src\middleware.ts:258:16)
                            at async next (E:\Koishi\dev\yesimbot\node_modules\@koishijs\core\src\middleware.ts:258:16)
                            at async next (E:\Koishi\dev\yesimbot\node_modules\@koishijs\core\src\middleware.ts:258:16)
```
而在finalReplyTo为"186782726"，groupId为"private:1762918301"时，报错却如下：
```
Error: Error with request send_private_msg, args: {"user_id":6,"message":[{"type":"at","data":{"qq":"1762918301","name":"Touch Night"}},{"type":"text","data":{"text":" 本大王见识过无数挑战，这些小点子也想困住本大 王？"}}]}, retcode: 1200
                            at _Internal._get (E:\Koishi\dev\yesimbot\node_modules\koishi-plugin-adapter-onebot\lib\index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
                            at async _Internal.<computed> [as sendPrivateMsg] (E:\Koishi\dev\yesimbot\node_modules\koishi-plugin-adapter-onebot\lib\index.js:162:20)
                            at async OneBotMessageEncoder.flush (E:\Koishi\dev\yesimbot\node_modules\koishi-plugin-adapter-onebot\lib\index.js:763:227)
                            at async OneBotMessageEncoder.send (E:\Koishi\dev\yesimbot\node_modules\@satorijs\core\src\message.ts:54:5)
                            at async Proxy.sendMessage (E:\Koishi\dev\yesimbot\node_modules\@satorijs\core\src\bot.ts:188:22)
                            at async <anonymous> (E:\Koishi\dev\yesimbot\external\yesimbot\src\index.ts:502:24)
                            at async next (E:\Koishi\dev\yesimbot\node_modules\@koishijs\core\src\middleware.ts:258:16)
                            at async next (E:\Koishi\dev\yesimbot\node_modules\@koishijs\core\src\middleware.ts:258:16)
                            at async next (E:\Koishi\dev\yesimbot\node_modules\@koishijs\core\src\middleware.ts:258:16)
```

改为`finalBotMsgId = (await session.bot.sendMessage(finalReplyTo, sentence, null))[0];`后恢复正常

@MiaowFISH

**Comment by Touch-Night** [comment]
私聊时的channelId是private:xxx

**Comment by MiaowFISH** [comment]
那改回来吧，mock插件年久失修，debug到现在还没找到兼容的方法。要测试的话我手动改一下好了

**Comment by MiaowFISH** [comment]
> 私聊时的channelId是private:xxx

是的，群聊是群号，私聊是private:xxx，所以一般情况下只需要传递channelId即可
至于为什么finalReplyId和groupId不一致时会报错，猜测应该是传入的session覆盖了先前的finalReplyId(koi貌似是根据channelId判断群聊或者私聊，用guildId指定从哪个群发起的群聊/私聊)导致channel和guild不匹配，错误地调用了send_private_msg

**Comment by MiaowFISH** [comment]
鉴于finalReplyId要么是groupId(quoteGroup也算)，要么是由LLM返回的replyTo，标题建议修改为`手动指定 finalReplyId 时，发送消息报错`（~~一句`不一致`让我多花了好多时间~~

**Comment by Touch-Night** [comment]
如果groupId和finalReplyId一致，即使finalReplyId是手动指定的，也不会报错
